---
version: edm_1_0

orchestration_technology:
  ansible:
    - dbms
    - db
  terraform:
    - ubuntu
  kubernetes:
    - pet_clinic_tomcat
    - pet_clinic
    - ubuntu2




components:

  ## Spring PetClinic Application

  pet_clinic:
    type: web_application
    artifacts:
      - war: ./files/petclinic/petclinic.war
    operations:
      configure: ./files/petclinic/configure.sh
      start: ./files/petclinic/start.sh
    relations:
      - hosted_on: pet_clinic_tomcat
      - connects_to: db
    interface:
      requires: # the values are calculated during runtime
        mysql-db:
          port:
            type: port
          user:
            type: string
    provides:
      pet_port: 42

  #tomcat
  pet_clinic_tomcat:
    type: tomcat
    operations:
      create: ./files/tomcat/create.sh
      start: ./files/tomcat/start.sh
    relations:
      - hosted_on: ubuntu2

  ## Database
  db:
    type: mysql_database
    properties:
      schema_name: petclinic
      user: pc
      password: petclinic
    artifacts:
      - sql: ./files/petclinic/schema.sql
    operations:
      configure: ./files/mysql_database/configure.sh
    relations:
      - hosted_on: dbms
    interface:
      capabilities:
        db:
          port:
            type: port
            value: 3307 #todo implement as scalar value
          user:
            type: string
            value: user #just read properties? by name/type

  dbms:
    type: mysql_dbms
    properties:
      root_password: petclinic
    operations:
      create: ./files/mysql_dbms/create.sh
      start: ./files/mysql_dbms/start.sh
    relations:
      - hosted_on: ubuntu

  ## Compute

  ubuntu:
    type: compute
    properties:
      machine_image: ubuntu
      instance_type: large
      key_name: edmm
      public_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqGKukO1De7zhZj6+H0qtjTkVxwTCpvKe4eCZ0
        FPqri0cb2JZfXJ/DgYSF6vUpwmJG8wVQZKjeGcjDOL5UlsuusFncCzWBQ7RKNUSesmQRMSGkVb1/
        3j+skZ6UtW+5u09lHNsj6tQ51s1SPrCBkedbNf0Tp0GbMJDyR4e9T04ZZwIDAQAB
        -----END PUBLIC KEY-----
    artifacts:
      - provider: ./files/ubuntu/openstack.json
    interface:
      capabilities:
        host:
          address:
            type: ip

  ubuntu2:
    type: compute
    properties:
      machine_image: ubuntu
      instance_type: large
      key_name: edmm
      public_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqGKukO1De7zhZj6+H0qtjTkVxwTCpvKe4eCZ0
        FPqri0cb2JZfXJ/DgYSF6vUpwmJG8wVQZKjeGcjDOL5UlsuusFncCzWBQ7RKNUSesmQRMSGkVb1/
        3j+skZ6UtW+5u09lHNsj6tQ51s1SPrCBkedbNf0Tp0GbMJDyR4e9T04ZZwIDAQAB
        -----END PUBLIC KEY-----
    artifacts:
      - provider: ./files/ubuntu/openstack.json
    interface:
      capabilities:
        host:
          address:
            type: ip


###############################################
## Component Types
###############################################
component_types:

  ## Generic Types

  base:
    extends: null
    description: The base type
    metadata: {}
    operations:
      create: ~
      configure: ~
      start: ~
      stop: ~
      delete: ~


  software_component:
    extends: base
    interface:
      requires:
        host:
          address:
            type: ip

  compute:
    extends: base
    properties:
      os_family:
        type: string
        description: Specifies the type of operating system
        default_value: linux
      machine_image:
        type: string
        description: The name of the machine image to use
      instance_type:
        type: string
        description: The name of the instance type to provision
      key_name:
        type: string
        description: The name of the key pair to use for authentication
      public_key:
        type: string
        description: The public key of the key pair to use for authentication

  web_server:
    extends: software_component
    properties:
      port:
        type: port
        default_value: 80



  web_application:
    extends: base
    interface:
      capabilities:
        app:
          http_port: # todo call it like this and use type?
            type: port
            default_value: 80
      requires:
        host:
          address:
            type: ip



  dbms:
    extends: software_component
    properties:
      port:
        type: integer
      root_password:
        type: string

  database:
    extends: base
    properties:
      schema_name:
        type: string
      user:
        type: string
      password:
        type: string
    interface:
      requires:
        host:
          address:
            type: ip



  ## Technology-specific Types

  tomcat:
    extends: web_server
    properties:
      port:
        type: port
        default_value: 8080

  mysql_dbms:
    extends: dbms
    properties:
      port:
        type: port
        default_value: 3306



  mysql_database:
    extends: database
    interface:
      capabilities:
        db:
          port:
            type: port
            default_value: 3306
          user:
            type: string.username


###############################################
## Relation Types
###############################################
relation_types:

  depends_on:
    extends: null
    properties: {}
    operations: {}

  hosted_on:
    extends: depends_on

  connects_to:
    extends: depends_on
